import { GetServerSideProps, GetServerSidePropsContext, type NextPage } from "next";
import Head from "next/head";

import Nav from "@/components/Nav";
import Content from "@/components/Dashboard";
import { getServerAuthSession } from "@/server/auth";

const Dashboard: NextPage = () => {
  return (
    <>
      <Head>
        <title>Dashboard – Financy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <Content />
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (ctx: GetServerSidePropsContext) => {
  const session = await getServerAuthSession(ctx);

  if (!session) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return {
    props: { session },
  };
};

export default Dashboard;
