import { type NextPage } from "next";
import Head from "next/head";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import DashboardComponent from "@/components/Dashboard";

const Dashboard: NextPage = () => {
  return (
    <>
      <Head>
        <title>Dashboard – Financy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <DashboardComponent />
      <Footer />
    </>
  );
};

export default Dashboard;
