import { type NextPage } from "next";
import { api } from "@/utils/api";
import Head from "next/head";
import Link from "next/link";
import Nav from "@/components/Nav";
import { Wallet } from "@prisma/client";

const Wallet = (props: { wallet: Wallet }) => {
  return (
    <div className="flex justify-between rounded-2xl border border-slate-100 bg-white p-8 shadow-md transition duration-300 hover:shadow-lg">
      <div className="flex flex-col gap-1">
        <div className="flex items-center">
          <Link
            href={`/wallet/${props.wallet.id}`}
            className="text-xl font-bold tracking-tight text-slate-800"
          >
            {props.wallet.name}
          </Link>
          <span className="ml-2 text-xs text-slate-600">
            ({props.wallet.currency})
          </span>
        </div>
        <p className="text-sm text-slate-600">{props.wallet.description}</p>
      </div>
      <div className="flex items-center">
        <span className="text-md font-semibold text-slate-700">$1,920.00</span>
      </div>
    </div>
  );
};

const Wallets = () => {
  const wallets = api.wallet.getAll.useQuery().data;

  return (
    <>
      {Array.isArray(wallets) && wallets.length && (
        <div className="flex w-full flex-col gap-6">
          <div className="flex items-center justify-between">
            <h2 className="text-3xl font-semibold tracking-tight text-slate-800">
              Your wallets
            </h2>
            <button className="rounded-lg bg-slate-800 px-2.5 py-1 text-sm text-slate-100">
              + Add wallet
            </button>
          </div>

          <div className="flex flex-col gap-4">
            {wallets.map((wallet) => (
              <Wallet key={wallet.id} wallet={wallet} />
            ))}
          </div>
        </div>
      )}
    </>
  );
};

const Transactions = () => {
  const transactions = api.transaction.getTen.useQuery().data;

  return (
    <>
      {Array.isArray(transactions) && transactions.length && (
        <div className="flex w-full flex-col gap-6">
          <div className="flex items-center justify-between">
            <h2 className="text-3xl font-semibold tracking-tight text-slate-800">
              Summary
            </h2>
            <button className="rounded-lg bg-slate-800 px-2.5 py-1 text-sm text-slate-100">
              + Add transaction
            </button>
          </div>
          <div className="flex flex-col gap-4">
            {transactions.map((transaction) => (
              <div
                key={transaction.id}
                className="flex justify-between rounded-2xl border border-slate-100 bg-white px-8 py-4 shadow-md transition duration-300 hover:shadow-lg"
              >
                <div className="flex flex-col gap-1">
                  <div className="flex items-center">
                    <Link
                      href={`/transaction/${transaction.id}`}
                      className="text-xl font-bold tracking-tight text-slate-800"
                    >
                      a
                    </Link>
                    <span className="ml-2 text-xs text-slate-600">
                      {transaction.type}
                    </span>
                  </div>
                  <p className="text-sm text-slate-600">
                    {transaction.description}
                  </p>
                </div>
                <div className="flex items-center">
                  <span className="text-md font-semibold text-slate-700">
                  {transaction.type === "EXPENSE" && ("-")}${transaction.amount}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </>
  );
};

const Dashboard: NextPage = () => {
  return (
    <>
      <Head>
        <title>User Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <main className="flex min-h-screen flex-col bg-white">
        <div className="flex w-full flex-col items-center px-4 py-12">
          <div className="mx-auto flex w-full max-w-screen-sm flex-col items-center gap-12">
            <Wallets />
            <Transactions/>
          </div>
        </div>
      </main>
    </>
  );
};

export default Dashboard;
