import { GetServerSideProps, GetServerSidePropsContext, type NextPage } from "next";
import Head from "next/head";

import Nav from "@/components/Nav";
import Content from "@/components/Landing";
import Footer from "@/components/Footer";
import { getServerAuthSession } from "@/server/auth";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Financy – Your finances, in one place</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <Content />
      <Footer />
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (ctx: GetServerSidePropsContext) => {
  const session = await getServerAuthSession(ctx);

  if (session) {
    return {
      redirect: {
        destination: "/dashboard",
        permanent: false,
      },
    };
  }

  return {
    props: { session },
  };
};

export default Home;
