import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "@/utils/api";

import { SignIn, SignInButton, UserButton, useUser } from "@clerk/nextjs";

const Auth = (props: { user: boolean }) => {
  return (
    <div>
      <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
      {!props.user && (
        <SignInButton>
          <button className="rounded-md bg-slate-900 px-4 py-2 text-white hover:bg-slate-800">
            Sign in
          </button>
        </SignInButton>
      )}
      {props.user && <UserButton />}
    </div>
  );
};

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center bg-slate-700">
        <div className="container flex flex-col items-center justify-center gap-4 px-4 py-16 ">
          <h1 className="text-5xl font-bold tracking-tight text-white">
            Finance App
          </h1>
          {user && <Auth user={!!user.isSignedIn} />}
        </div>
      </main>
    </>
  );
};

export default Home;
