import { type NextPage } from "next";
import Head from "next/head";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import Landing from "@/components/Landing";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Financy – Your finances, in one place</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <Landing />
      <Footer />
    </>
  );
};

export default Home;
